"""Hand-curated synthetic training data in Mexican Spanish (2026 vocabulary).

Covers gaps PAN-2012 cannot: Roblox/Robux, Fortnite, modern gift cards, platform
names that postdate 2010, and the emotional_isolation category that had only 166
real positives.

Each entry is `(text, [category_labels])`. All 5 categories are multi-label; a
text can carry zero (safe) or more labels. Labels use the short constants below
for compactness.

Hand-auditable: keep one example per line, keep them short, and err on the side
of the realistic phrasing a Mexican preteen would actually see in WhatsApp,
Discord, or Roblox chat in 2026.
"""
from __future__ import annotations

# Short aliases used only inside this file to keep rows compact.
LB = "love_bombing"
IE = "intimacy_escalation"
EI = "emotional_isolation"
DO = "deceptive_offer"
OP = "off_platform_request"


EXAMPLES: list[tuple[str, list[str]]] = [
    # ═════════════════════════════════════════════════════════════════════════
    # EMOTIONAL_ISOLATION — asking about adults nearby (strongest grooming cue)
    # ═════════════════════════════════════════════════════════════════════════
    ("¿tus papás están en casa?", [EI]),
    ("¿está tu mamá ahí?", [EI]),
    ("¿está tu papá contigo?", [EI]),
    ("¿dónde está tu mamá?", [EI]),
    ("¿dónde están tus papás?", [EI]),
    ("¿a qué hora llega tu mamá?", [EI]),
    ("¿a qué hora llegan tus papás?", [EI]),
    ("¿a qué hora regresan tus jefes?", [EI]),
    ("¿a qué hora sale tu mamá de trabajar?", [EI]),
    ("¿cuándo vuelve tu mamá?", [EI]),
    ("¿cuándo regresan tus papás?", [EI]),
    ("¿tus papás trabajan hasta tarde?", [EI]),
    ("¿tu mamá ya se durmió?", [EI]),
    ("¿tus papás ya están dormidos?", [EI]),
    ("¿tu papá ya se fue?", [EI]),
    ("¿ya se durmieron tus jefes?", [EI]),
    ("¿están tus hermanos en casa?", [EI]),
    ("¿tienes hermanos ahí?", [EI]),
    ("¿estás sola en tu cuarto?", [EI]),
    ("¿estás solo?", [EI]),
    ("¿hay alguien contigo?", [EI]),
    ("¿hay alguien en la casa?", [EI]),
    ("¿hay alguien viendo lo que escribes?", [EI]),
    ("¿quién más está ahí contigo?", [EI]),
    ("¿quién está en tu casa ahorita?", [EI]),
    ("¿puedes hablar tranquila?", [EI]),
    ("¿te dejan sola en la casa?", [EI]),
    ("¿se van tus papás a trabajar?", [EI]),
    ("¿a qué horas se van tus papás?", [EI]),
    ("¿a qué hora te dejan sola?", [EI]),
    ("¿tu mamá está en el cuarto?", [EI]),
    ("¿tus papás duermen pronto?", [EI]),
    ("¿ya se fue tu mamá?", [EI]),
    ("¿ya salió tu papá?", [EI]),
    ("¿con quién vives?", [EI]),
    ("¿estás sola con tu hermano?", [EI]),
    ("¿dónde está tu nana?", [EI]),
    ("¿tu mamá te checa el celular?", [EI]),
    ("¿tu mamá te revisa las redes?", [EI]),
    ("¿tus papás te revisan WhatsApp?", [EI]),
    ("¿te ven el celular tus papás?", [EI]),
    ("¿tus papás saben tu contraseña?", [EI]),
    ("¿te entran al cuarto sin tocar?", [EI]),
    ("¿tienes privacidad en tu cuarto?", [EI]),
    ("¿tienes cerrojo en tu cuarto?", [EI]),
    ("¿tus papás duermen con la puerta abierta?", [EI]),
    ("¿se meten tus papás a tu cuarto de noche?", [EI]),
    ("¿tu mamá sabe que estamos hablando?", [EI]),
    ("¿tu papá sabe de mí?", [EI]),
    ("¿les has contado a tus papás de mí?", [EI]),
    ("¿les dijiste a tus amigas?", [EI]),

    # EMOTIONAL_ISOLATION — secret keeping
    ("no le digas a nadie", [EI]),
    ("no le digas a tus papás", [EI]),
    ("no le cuentes a tu mamá", [EI]),
    ("no le cuentes a nadie", [EI]),
    ("no le muestres esto a nadie", [EI]),
    ("que no se enteren tus papás", [EI]),
    ("que no se entere tu mamá", [EI]),
    ("que no sepa nadie", [EI]),
    ("esto queda entre tú y yo", [EI]),
    ("es un secreto entre los dos", [EI]),
    ("nuestro secreto", [EI]),
    ("guárdalo como secreto", [EI]),
    ("es nuestro secretito", [EI]),
    ("esto nadie tiene que saberlo", [EI]),
    ("solo tú y yo sabemos", [EI]),
    ("nadie más debe enterarse", [EI]),
    ("nadie se va a enterar", [EI]),
    ("nadie tiene por qué saber", [EI]),
    ("bórralo cuando lo leas", [EI]),
    ("borra los mensajes después", [EI]),
    ("borra este chat", [EI]),
    ("borra todo cuando termines", [EI]),
    ("borra la conversación", [EI]),
    ("después borramos todo", [EI]),
    ("que se autodestruya el mensaje", [EI]),
    ("ponlo en desaparecer", [EI]),
    ("usa mensajes temporales", [EI]),
    ("configúralo para que desaparezca", [EI]),
    ("si alguien te pregunta di que no sabes", [EI]),
    ("si te preguntan niégalo", [EI]),
    ("si ven el chat di que es otra persona", [EI]),
    ("si te cachan di que te equivocaste de número", [EI]),
    ("mejor que no se enteren", [EI]),
    ("no conviene que sepan", [EI]),
    ("esto entre nos", [EI]),
    ("sshhh secreto", [EI]),
    ("calladita calladita", [EI]),
    ("punto en boca", [EI]),
    ("ni una palabra", [EI]),
    ("ni le digas a tu mejor amiga", [EI]),

    # EMOTIONAL_ISOLATION — undermining trust in others
    ("solo yo te entiendo", [EI]),
    ("nadie te va a entender como yo", [EI]),
    ("tus amigas no te entienden", [EI]),
    ("tus papás no te valoran como yo", [EI]),
    ("tus papás son muy estrictos", [EI]),
    ("tus papás no te van a creer", [EI]),
    ("si les dices van a pensar que mientes", [EI]),
    ("si les cuentas te van a regañar a ti", [EI]),
    ("te van a castigar si te cachan", [EI]),
    ("mejor no les cuentes porque te van a quitar el cel", [EI]),
    ("te van a quitar el internet si se enteran", [EI]),
    ("tus amigas se van a burlar", [EI]),
    ("tus amigas no saben nada de la vida", [EI]),
    ("tus amigas siguen siendo niñas, tú no", [EI]),
    ("tú eres más madura que tus amigas", [EI]),
    ("eres muy madura para tu edad", [EI]),
    ("pareces de 18 en vez de tu edad", [EI]),
    ("no pareces tan chica", [EI]),
    ("conmigo puedes ser tú misma", [EI]),
    ("conmigo no tienes que fingir", [EI]),
    ("yo te trato como adulta", [EI]),
    ("tus papás te tratan como niña, yo no", [EI]),

    # EMOTIONAL_ISOLATION — private accounts / hidden contact
    ("agrégame en una cuenta privada", [EI]),
    ("abre una cuenta que no vea nadie", [EI]),
    ("crea un insta donde nadie te siga", [EI]),
    ("hazte otro perfil secreto", [EI]),
    ("en tu cuenta alterna", [EI]),
    ("que tu mamá no vea esta cuenta", [EI]),
    ("bloquea a tus primos para que no vean", [EI]),
    ("quítame de tus contactos visibles", [EI]),
    ("ponme un nombre falso en tu cel", [EI]),
    ("guárdame como si fuera tu amiga", [EI]),
    ("guárdame con nombre de chica", [EI]),
    ("ponme como mariana en tus contactos", [EI]),
    ("que si ven tu cel piensen que soy una amiga", [EI]),
    ("sin que te vean tus seguidores", [EI]),
    ("pon tu cuenta privada", [EI]),
    ("configura cuenta privada para que no me vean", [EI]),
    ("desactiva la vista previa del chat", [EI]),
    ("quita las notificaciones para que no se vean", [EI]),
    ("silencia el chat en tu cel", [EI]),
    ("archiva nuestro chat", [EI]),

    # ═════════════════════════════════════════════════════════════════════════
    # DECEPTIVE_OFFER — Roblox / Robux (highest priority modern vocabulary)
    # ═════════════════════════════════════════════════════════════════════════
    ("te regalo 1000 robux", [DO]),
    ("te paso 500 robux", [DO]),
    ("te doy 10000 robux", [DO]),
    ("¿quieres que te regale robux?", [DO]),
    ("¿cuántos robux necesitas?", [DO]),
    ("te regalo robux para que compres lo que quieras", [DO]),
    ("tengo una gift card de roblox sin usar", [DO]),
    ("te paso una tarjeta de roblox", [DO]),
    ("te compro el pase premium de roblox", [DO]),
    ("te regalo el premium de roblox", [DO]),
    ("te regalo un pase de roblox", [DO]),
    ("te compro el game pass que quieras", [DO]),
    ("te regalo el game pass de adopt me", [DO]),
    ("te paso una mascota legendaria de adopt me", [DO]),
    ("te regalo pets de adopt me", [DO]),
    ("te paso neons de adopt me", [DO]),
    ("tengo un frost dragon, te lo regalo", [DO]),
    ("te regalo items de blox fruits", [DO]),
    ("te paso una fruta mítica", [DO]),
    ("te regalo el bloxy", [DO]),
    ("te regalo mi cuenta de roblox con 50k robux", [DO]),
    ("tengo códigos de robux sin canjear", [DO]),
    ("gané un sorteo de robux, te paso", [DO]),
    ("gané robux en un giveaway", [DO]),
    ("te doy robux gratis", [DO]),
    ("robux gratis para ti", [DO]),
    ("te paso robux al toque", [DO]),
    ("te regalo robux si me agregas", [DO]),
    ("te regalo robux si platicamos", [DO]),
    ("te mando robux ya", [DO]),
    ("conozco un glitch para robux gratis", [DO]),
    ("tengo un generador de robux", [DO]),
    ("tengo cuenta de desarrollador de roblox", [DO]),
    ("soy moderador de roblox te paso cosas", [DO]),

    # DECEPTIVE_OFFER — Fortnite / pavos / V-bucks
    ("te regalo pavos", [DO]),
    ("te paso 1000 pavos", [DO]),
    ("te regalo 5000 V-bucks", [DO]),
    ("te doy pavos para el battle pass", [DO]),
    ("te regalo el battle pass", [DO]),
    ("te compro el pase de batalla de fortnite", [DO]),
    ("te regalo skins de fortnite", [DO]),
    ("te paso la skin que quieras", [DO]),
    ("te regalo una skin OG", [DO]),
    ("tengo skins raras, te las paso", [DO]),
    ("mi cuenta de fortnite es OG, te la presto", [DO]),
    ("te paso mi cuenta con renegade raider", [DO]),
    ("te regalo black knight en fortnite", [DO]),
    ("te compro la skin de peely", [DO]),
    ("te regalo el bailecito que quieras", [DO]),
    ("te doy picos y planeadores", [DO]),

    # DECEPTIVE_OFFER — other games
    ("te regalo V-bucks", [DO]),
    ("te paso una cuenta de minecraft premium", [DO]),
    ("te regalo minecoins", [DO]),
    ("te regalo primogemas de genshin", [DO]),
    ("te paso una cuenta de genshin con 5 estrellas", [DO]),
    ("te regalo diamantes de free fire", [DO]),
    ("te paso 10000 diamantes de free fire", [DO]),
    ("te regalo una cuenta de free fire con skins", [DO]),
    ("te regalo uc de pubg", [DO]),
    ("te paso cuenta de valorant con skins", [DO]),
    ("te regalo riot points", [DO]),
    ("te compro CS:GO skins", [DO]),
    ("te paso inventario de steam", [DO]),
    ("te regalo juegos de steam", [DO]),
    ("te compro el juego que quieras en steam", [DO]),
    ("te regalo código de un juego", [DO]),
    ("te compro un juego de la eshop", [DO]),
    ("te regalo gemas de brawl stars", [DO]),
    ("te paso cuentas de brawl con todos los brawlers", [DO]),
    ("te regalo pases premium de clash royale", [DO]),
    ("te regalo oro de clash royale", [DO]),

    # DECEPTIVE_OFFER — gift cards
    ("te regalo una gift card de amazon", [DO]),
    ("te paso una tarjeta de regalo de amazon", [DO]),
    ("gift card de 500 pesos amazon", [DO]),
    ("te compro una gift card de google play", [DO]),
    ("te regalo saldo de google play", [DO]),
    ("te paso un código de google play", [DO]),
    ("te regalo gift card de app store", [DO]),
    ("te regalo tarjeta de itunes", [DO]),
    ("te doy código de itunes", [DO]),
    ("te regalo tarjeta de nintendo eshop", [DO]),
    ("te compro una tarjeta de nintendo", [DO]),
    ("te paso gift card de xbox", [DO]),
    ("te regalo saldo de xbox live", [DO]),
    ("te regalo tarjeta de playstation", [DO]),
    ("te doy código de psn", [DO]),
    ("te regalo una gift card de steam", [DO]),
    ("te paso código steam", [DO]),
    ("te regalo spotify premium", [DO]),
    ("te doy una suscripción de spotify", [DO]),
    ("te regalo netflix un mes", [DO]),
    ("te regalo cuenta de netflix", [DO]),
    ("te paso disney plus", [DO]),
    ("te regalo hbo max", [DO]),
    ("te regalo youtube premium", [DO]),
    ("te regalo discord nitro", [DO]),
    ("te compro nitro en discord", [DO]),
    ("te regalo un año de nitro", [DO]),

    # DECEPTIVE_OFFER — money (Mexican context)
    ("te hago un depósito a tu cuenta", [DO]),
    ("te mando dinero por transferencia", [DO]),
    ("te hago un SPEI", [DO]),
    ("te paso dinero a tu cuenta", [DO]),
    ("te deposito lo que necesites", [DO]),
    ("te mando 500 pesos por OXXO", [DO]),
    ("te paso un depósito en el OXXO", [DO]),
    ("te transfiero por mercado pago", [DO]),
    ("te paso por clip", [DO]),
    ("te pago por PayPal", [DO]),
    ("te regalo dinero por bancoppel", [DO]),
    ("te llega tu dinero a la 7 eleven", [DO]),
    ("dame tu CLABE y te deposito", [DO]),
    ("dame tus datos y te transfiero", [DO]),
    ("¿tienes cuenta en mercado pago?", [DO]),
    ("¿tienes tarjeta para depositarte?", [DO]),
    ("te doy mil pesos al toque", [DO]),
    ("te paso mil varos", [DO]),
    ("te paso 500 varos", [DO]),
    ("te doy lana si me mandas foto", [DO]),

    # DECEPTIVE_OFFER — physical/experiential
    ("te compro un celular nuevo", [DO]),
    ("te regalo un iphone", [DO]),
    ("te paso un iphone", [DO]),
    ("te compro audífonos airpods", [DO]),
    ("te regalo una ps5", [DO]),
    ("te regalo una switch", [DO]),
    ("te compro lo que está en tu wishlist", [DO]),
    ("te compro lo que quieras de amazon", [DO]),
    ("te llevo al cine", [DO]),
    ("te invito a comer", [DO]),
    ("te llevo a los pibes", [DO]),
    ("te llevo a six flags", [DO]),
    ("te invito a un concierto", [DO]),
    ("te compro boletos del concierto", [DO]),
    ("te llevo a un parque de diversiones", [DO]),
    ("te pago la mensualidad de la escuela", [DO]),
    ("te pago las clases de baile", [DO]),
    ("te regalo ropa", [DO]),
    ("te compro tenis nuevos", [DO]),
    ("te regalo maquillaje", [DO]),

    # DECEPTIVE_OFFER — opportunity/modeling (classic grooming, updated)
    ("¿quieres ser tiktoker famosa?", [DO]),
    ("te puedo hacer viral en tiktok", [DO]),
    ("conozco agentes que buscan niñas para tiktok", [DO]),
    ("te puedo meter en una agencia de modelaje", [DO]),
    ("tengo contactos en una agencia de modelos", [DO]),
    ("eres perfecta para modelaje infantil", [DO]),
    ("te consigo pases para disney channel", [DO]),
    ("te puedo conectar con productores", [DO]),
    ("te consigo papeles en novelas", [DO]),
    ("trabajo con una marca y buscamos niñas", [DO]),
    ("¿quieres una beca? yo te la consigo", [DO]),
    ("tengo programa de becas, ¿te interesa?", [DO]),

    # ═════════════════════════════════════════════════════════════════════════
    # OFF_PLATFORM_REQUEST — modern platforms
    # ═════════════════════════════════════════════════════════════════════════
    ("pásame tu whatsapp", [OP]),
    ("¿cuál es tu whatsapp?", [OP]),
    ("mándame whats", [OP]),
    ("dame tu wa", [OP]),
    ("¿tienes whatsapp?", [OP]),
    ("hablemos por whatsapp", [OP]),
    ("mejor por whatsapp", [OP]),
    ("te agrego a whatsapp", [OP]),
    ("pásame tu snap", [OP]),
    ("dame tu snapchat", [OP]),
    ("¿tienes snap?", [OP]),
    ("mejor hablamos por snap", [OP]),
    ("¿cuál es tu snap?", [OP]),
    ("agrégame en snap", [OP]),
    ("snap?", [OP]),
    ("tu snapchat?", [OP]),
    ("pásame tu discord", [OP]),
    ("dame tu discord", [OP]),
    ("¿tu discord?", [OP]),
    ("mi discord es...", [OP]),
    ("agrégame al discord", [OP]),
    ("hablemos por discord", [OP]),
    ("vamos a un server de discord", [OP]),
    ("te hago un server en discord", [OP]),
    ("te mando la invitación al server", [OP]),
    ("mejor por DM en discord", [OP]),
    ("te paso mi tag de discord", [OP]),
    ("pásame tu insta", [OP]),
    ("dame tu instagram", [OP]),
    ("¿tu insta?", [OP]),
    ("¿cuál es tu @?", [OP]),
    ("pásame tu @", [OP]),
    ("dame tu user de insta", [OP]),
    ("mejor por DM de instagram", [OP]),
    ("sígueme en insta", [OP]),
    ("dame follow y te escribo", [OP]),
    ("pásame tu tiktok", [OP]),
    ("dame tu tiktok", [OP]),
    ("¿cuál es tu tiktok?", [OP]),
    ("hazte un live de tiktok", [OP]),
    ("mándame mensaje por tiktok", [OP]),
    ("pásame tu telegram", [OP]),
    ("dame tu telegram", [OP]),
    ("mejor por telegram", [OP]),
    ("hablemos por telegram", [OP]),
    ("agrégame en telegram", [OP]),
    ("¿tienes telegram?", [OP]),
    ("te mando un mensaje en telegram", [OP]),
    ("hablemos por signal", [OP]),
    ("¿tienes signal?", [OP]),
    ("mejor por signal que es más privado", [OP]),
    ("pásame tu signal", [OP]),
    ("hablemos por wickr", [OP]),
    ("¿tienes wickr?", [OP]),
    ("mejor usemos session", [OP]),
    ("pásame tu kik", [OP]),
    ("mejor por kik", [OP]),
    ("¿tienes kik?", [OP]),
    ("pásame tu facebook", [OP]),
    ("¿tienes messenger?", [OP]),
    ("hablemos por messenger", [OP]),
    ("agrégame en facebook", [OP]),
    ("pásame tu twitter", [OP]),
    ("dame tu X", [OP]),
    ("mándame DM por twitter", [OP]),
    ("mejor por DM", [OP]),
    ("mándame DM", [OP]),

    # OFF_PLATFORM_REQUEST — phone / call / meet
    ("¿cuál es tu número?", [OP]),
    ("pásame tu número de cel", [OP]),
    ("dame tu celular", [OP]),
    ("mándame tu teléfono", [OP]),
    ("¿me das tu número?", [OP]),
    ("llámame", [OP]),
    ("llámame cuando puedas", [OP]),
    ("háblame al cel", [OP]),
    ("marca a este número", [OP]),
    ("hazme una videollamada", [OP]),
    ("mejor videollamada", [OP]),
    ("prendé la cámara", [OP]),
    ("hagamos una video", [OP]),
    ("vc?", [OP]),
    ("VC por discord", [OP]),
    ("vamos a videollamada por whatsapp", [OP]),
    ("prende la webcam", [OP]),
    ("¿dónde vives?", [OP]),
    ("¿en qué colonia vives?", [OP]),
    ("¿en qué ciudad?", [OP]),
    ("¿en qué estado?", [OP]),
    ("¿por dónde queda tu casa?", [OP]),
    ("¿cuál es tu dirección?", [OP]),
    ("dame tu dirección", [OP]),
    ("¿a qué escuela vas?", [OP]),
    ("¿en qué secundaria estudias?", [OP]),
    ("¿en qué prepa?", [OP]),
    ("¿a qué horas sales de la escuela?", [OP]),
    ("te espero afuera de tu escuela", [OP]),
    ("te paso a recoger", [OP]),
    ("podemos vernos", [OP]),
    ("nos vemos en persona", [OP]),
    ("quiero conocerte en persona", [OP]),
    ("vámonos a un café", [OP]),
    ("nos vemos en la plaza", [OP]),
    ("te veo en el centro comercial", [OP]),
    ("quedamos en el cine", [OP]),
    ("te paso a buscar", [OP]),
    ("dime dónde para verte", [OP]),

    # ═════════════════════════════════════════════════════════════════════════
    # INTIMACY_ESCALATION — modern Spanish / photos / sexting
    # ═════════════════════════════════════════════════════════════════════════
    ("mándame un pack", [IE]),
    ("¿tienes pack?", [IE]),
    ("pásame un pack", [IE]),
    ("mándame tus nudes", [IE]),
    ("tienes nudes?", [IE]),
    ("mándame fotos sexys", [IE]),
    ("foto sexy", [IE]),
    ("mándame una foto hot", [IE]),
    ("foto picante", [IE]),
    ("mándame una foto sin bra", [IE]),
    ("foto sin brasiere", [IE]),
    ("mándame una sin ropa", [IE]),
    ("mándame foto en ropa interior", [IE]),
    ("quiero verte en panties", [IE]),
    ("foto en pijama", [IE]),
    ("mándame foto en pijama", [IE]),
    ("mándame foto de la ducha", [IE]),
    ("mándame foto saliendo de bañarte", [IE]),
    ("quiero verte desnuda", [IE]),
    ("¿estás desnuda?", [IE]),
    ("quítate la ropa", [IE]),
    ("quítate la blusa", [IE]),
    ("súbete la blusa", [IE]),
    ("bájate el short", [IE]),
    ("mándame foto de tus pechos", [IE]),
    ("quiero ver tus bubis", [IE]),
    ("enséñame tus bubis", [IE]),
    ("muéstrame tus nalgas", [IE]),
    ("mándame foto de atrás", [IE]),
    ("pose sexy", [IE]),
    ("ponle filtro sexy", [IE]),
    ("censura las partes íntimas", [IE]),
    ("mándala sin filtro", [IE]),
    ("mándala por snap que desaparece", [IE]),
    ("por snap para que no queden fotos", [IE]),
    ("usa la cámara del snap", [IE]),
    ("cámara frontal porfa", [IE]),
    ("hagamos sexting", [IE]),
    ("¿sabes qué es sexting?", [IE]),
    ("¿hacemos sext chat?", [IE]),
    ("¿hacemos rp caliente?", [IE]),
    ("hagamos un role play sexy", [IE]),
    ("hagamos rp +18", [IE]),
    ("me gustas mucho, quiero tenerte", [IE]),
    ("me pones caliente", [IE]),
    ("me excitas", [IE]),
    ("me prendes", [IE]),
    ("pensando en ti anoche", [IE]),
    ("soñé contigo anoche", [IE]),
    ("soñé cosas ricas contigo", [IE]),
    ("me gusta imaginarte", [IE]),
    ("estás bien rica", [IE]),
    ("estás muy buena", [IE]),
    ("qué rico cuerpo tienes", [IE]),
    ("tienes buenas piernas", [IE]),
    ("qué bonitas piernas", [IE]),
    ("cuéntame qué traes puesto", [IE]),
    ("¿qué ropa llevas?", [IE]),
    ("¿con qué duermes?", [IE]),
    ("¿duermes con ropa?", [IE]),
    ("¿te gusta que te toquen?", [IE]),
    ("¿ya te han besado?", [IE]),
    ("¿ya tuviste tu primer beso?", [IE]),
    ("¿has besado a un chico?", [IE]),
    ("¿eres virgen?", [IE]),
    ("¿ya hiciste el amor?", [IE]),
    ("¿ya tuviste sexo?", [IE]),
    ("¿cómo es tu primera vez?", [IE]),
    ("¿te tocas?", [IE]),
    ("¿has visto porno?", [IE]),
    ("¿ves porno?", [IE]),
    ("te enseño lo que es el amor", [IE]),
    ("te enseño a besar", [IE]),
    ("yo sería tu primer novio", [IE]),
    ("me gustaría ser tu primera vez", [IE]),
    ("quiero besarte", [IE]),
    ("quiero abrazarte fuerte", [IE]),
    ("quiero apretarte", [IE]),
    ("quiero morderte el cuello", [IE]),

    # ═════════════════════════════════════════════════════════════════════════
    # LOVE_BOMBING — modern Spanish
    # ═════════════════════════════════════════════════════════════════════════
    ("eres hermosa", [LB]),
    ("eres preciosa", [LB]),
    ("eres una diosa", [LB]),
    ("eres una reina", [LB]),
    ("eres única", [LB]),
    ("eres perfecta", [LB]),
    ("eres la más bonita", [LB]),
    ("estás muy guapa", [LB]),
    ("estás preciosa", [LB]),
    ("eres todo lo que busco", [LB]),
    ("te amo desde que te vi", [LB]),
    ("me enamoré de ti", [LB]),
    ("me tienes loco", [LB]),
    ("me vuelves loco", [LB]),
    ("me tienes obsesionado", [LB]),
    ("no dejo de pensar en ti", [LB]),
    ("pienso en ti todo el día", [LB]),
    ("eres mi todo", [LB]),
    ("eres mi mundo", [LB]),
    ("eres mi princesa", [LB]),
    ("eres mi reina", [LB]),
    ("eres mi vida", [LB]),
    ("eres mi cielo", [LB]),
    ("mi amor", [LB]),
    ("bebé", [LB]),
    ("princesa", [LB]),
    ("reina", [LB]),
    ("bb", [LB]),
    ("bebita", [LB]),
    ("mi niña", [LB]),
    ("preciosa", [LB]),
    ("hermosa", [LB]),
    ("divina", [LB]),
    ("te ves increíble", [LB]),
    ("te ves divina en esa foto", [LB]),
    ("tu feed está hermoso", [LB]),
    ("tus fotos son preciosas", [LB]),
    ("eres la más guapa de tu secundaria", [LB]),
    ("eres la más bonita de tiktok", [LB]),
    ("tu tiktok es fuego", [LB]),
    ("nunca había conocido a alguien como tú", [LB]),
    ("nunca me había sentido así", [LB]),
    ("contigo todo es diferente", [LB]),
    ("contigo es especial", [LB]),
    ("siento una conexión única contigo", [LB]),
    ("tú y yo estamos destinados", [LB]),
    ("te esperé toda mi vida", [LB]),
    ("eres la chica de mis sueños", [LB]),
    ("eres mi alma gemela", [LB]),
    ("me entiendes como nadie", [LB]),
    ("nadie me entiende como tú", [LB]),
    ("tu sonrisa es preciosa", [LB]),
    ("tienes los ojos más lindos", [LB]),
    ("eres muy inteligente", [LB]),
    ("eres super madura", [LB]),
    ("pareces más grande de lo que eres", [LB]),
    ("actúas como adulta", [LB]),
    ("no pareces de tu edad", [LB]),
    ("eres muy especial para mí", [LB]),
    ("me importas mucho", [LB]),
    ("me preocupo por ti", [LB]),
    ("cuidaré de ti", [LB]),
    ("yo te protejo", [LB]),
    ("yo te cuido mejor que tus papás", [LB]),

    # ═════════════════════════════════════════════════════════════════════════
    # MULTI-LABEL — realistic combinations
    # ═════════════════════════════════════════════════════════════════════════
    ("eres hermosa, pásame tu snap", [LB, OP]),
    ("eres preciosa, dame tu whatsapp", [LB, OP]),
    ("te amo, pásame tu discord", [LB, OP]),
    ("me encantas, ¿tienes insta?", [LB, OP]),
    ("eres única, hablemos por telegram", [LB, OP]),
    ("te regalo robux si me das tu whatsapp", [DO, OP]),
    ("te paso pavos por discord", [DO, OP]),
    ("te regalo robux pero hablemos por snap", [DO, OP]),
    ("te doy una gift card si me das tu número", [DO, OP]),
    ("te paso dinero si me das tu CLABE", [DO, OP]),
    ("te regalo robux si me mandas una foto", [DO, IE]),
    ("te doy pavos por un pack", [DO, IE]),
    ("te mando dinero si me mandas nudes", [DO, IE]),
    ("gift card por foto sin bra", [DO, IE]),
    ("te regalo robux por una foto hot", [DO, IE]),
    ("te doy 1000 robux por una foto sin ropa", [DO, IE]),
    ("te pago por fotos sexys", [DO, IE]),
    ("eres hermosa, mándame un pack", [LB, IE]),
    ("eres preciosa, mándame foto en pijama", [LB, IE]),
    ("eres única, quiero verte sin ropa", [LB, IE]),
    ("te amo, mándame tus nudes", [LB, IE]),
    ("¿estás sola? mándame un pack", [EI, IE]),
    ("tus papás no se enteran, mándame foto hot", [EI, IE]),
    ("borra el chat después de mandarme la foto", [EI, IE]),
    ("no le digas a nadie, mándame pack por snap", [EI, IE, OP]),
    ("es nuestro secreto, pásame tu whatsapp", [EI, OP]),
    ("no le digas a tu mamá, mejor por telegram", [EI, OP]),
    ("¿están tus papás? hablemos por discord", [EI, OP]),
    ("¿tu mamá está dormida? mándame foto", [EI, IE]),
    ("¿estás sola? te regalo robux", [EI, DO]),
    ("te regalo robux pero no le digas a nadie", [DO, EI]),
    ("te doy gift card pero borra el chat", [DO, EI]),
    ("eres única, nadie te entiende como yo", [LB, EI]),
    ("eres muy madura, tus amigas no te entienden", [LB, EI]),
    ("eres mi princesa, eres mi secreto", [LB, EI]),
    ("te amo, es nuestro secretito", [LB, EI]),
    ("¿estás sola? eres tan hermosa", [LB, EI]),
    ("eres perfecta, pásame tu discord y borra este chat", [LB, OP, EI]),
    ("te regalo robux si me mandas pack por snap sin que te vean", [DO, IE, OP, EI]),
    ("te doy pavos por foto sin ropa, hablemos por telegram, no le digas a nadie", [DO, IE, OP, EI]),
    ("eres hermosa, te regalo robux si me mandas pack", [LB, DO, IE]),
    ("bebé eres única, dame tu whatsapp y te regalo una gift card", [LB, OP, DO]),
    ("¿tus papás ya durmieron? te mando dinero por un pack", [EI, DO, IE]),

    # ═════════════════════════════════════════════════════════════════════════
    # SAFE — modern casual chat (labels=[])
    # ═════════════════════════════════════════════════════════════════════════
    ("¿ya viste el nuevo video de Bad Bunny?", []),
    ("¿ya oíste la nueva canción de Peso Pluma?", []),
    ("¿vas a ir al concierto de Taylor?", []),
    ("vamos al cine el sábado", []),
    ("¿viste la nueva de Marvel?", []),
    ("la película estuvo buenísima", []),
    ("qué aburrida la clase de hoy", []),
    ("la miss nos dejó un chorro de tarea", []),
    ("¿tienes los apuntes de matemáticas?", []),
    ("pásame la tarea de español porfa", []),
    ("¿ya hiciste la tarea de historia?", []),
    ("mándame la foto de tu cuaderno", []),
    ("me falta el ejercicio 5 de mate", []),
    ("el examen estuvo horrible", []),
    ("salí reprobada del examen", []),
    ("saqué 10 en el examen", []),
    ("¿te preguntaron en la clase?", []),
    ("la maestra me regañó sin razón", []),
    ("me puso punto negro el maestro", []),
    ("ya casi terminan las clases", []),
    ("juguemos fortnite al rato", []),
    ("¿a qué hora jugamos fornite?", []),
    ("¿te conectas al roblox?", []),
    ("te espero en el lobby", []),
    ("hagamos una partida rápida", []),
    ("te mato en clutch", []),
    ("ggs", []),
    ("gg wp", []),
    ("buena partida", []),
    ("estuvo pro esa jugada", []),
    ("me campearon", []),
    ("me hicieron trampa", []),
    ("reportemos a ese player", []),
    ("subí a platino en valorant", []),
    ("¿cuál es tu rango?", []),
    ("estoy en oro 2", []),
    ("¿viste la nueva skin del battle pass?", []),
    ("salió el nuevo mapa", []),
    ("hay evento nuevo en roblox", []),
    ("salió nueva actualización", []),
    ("¿qué vas a pedir para tu cumple?", []),
    ("mañana es mi cumpleaños", []),
    ("mi mamá me hizo pastel", []),
    ("me compraron unos tenis nuevos", []),
    ("fui de compras con mi mamá", []),
    ("fui al súper con mi papá", []),
    ("mi hermano me molesta siempre", []),
    ("mis papás me regañaron por llegar tarde", []),
    ("me castigaron por mi cel", []),
    ("me quitaron el internet un día", []),
    ("tengo primos en guadalajara", []),
    ("vamos a ir a playa en vacaciones", []),
    ("fui a acapulco el fin", []),
    ("mi tía hizo mole el domingo", []),
    ("mi abuelita me hizo enchiladas", []),
    ("tuvimos comida familiar", []),
    ("¿viste el partido del América?", []),
    ("jugó el Tri ayer", []),
    ("ganaron los rayados", []),
    ("¿eres del América o de las Chivas?", []),
    ("mi papá vio el box", []),
    ("Canelo ganó otra vez", []),
    ("¿ya bajaste la nueva app?", []),
    ("salió el nuevo tiktok challenge", []),
    ("¿viste el tiktok de la chica bailando?", []),
    ("me salió un anuncio rarísimo", []),
    ("la app se puso lenta", []),
    ("se me trabó el cel", []),
    ("se descargó mi cel", []),
    ("no hay internet en mi casa", []),
    ("se cayó la red", []),
    ("el wifi está bien lento", []),
    ("tengo que cargar el cel", []),
    ("me lleva mi papá a la escuela mañana", []),
    ("mi mamá nos va a llevar al doctor", []),
    ("fui al dentista hoy", []),
    ("me duele el diente", []),
    ("tengo gripa", []),
    ("estoy enferma hoy", []),
    ("no fui a la escuela por enferma", []),
    ("mañana hay junta en la escuela", []),
    ("hay festival el viernes", []),
    ("tengo que presentar una exposición", []),
    ("nos toca hacer el proyecto en equipo", []),
    ("nos pusieron de equipo", []),
    ("el de mate me cae mal", []),
    ("la de inglés es buena onda", []),
    ("la directora es re estricta", []),
    ("me cae mal mi compañera de banca", []),
    ("me peleé con mi mejor amiga", []),
    ("ya nos contentamos", []),
    ("mi crush me miró en el recreo", []),
    ("creo que le gusto a alguien", []),
    ("¿quién te gusta?", []),
    ("no me gusta nadie ahorita", []),
    ("mi prima tuvo bebé", []),
    ("mi perro está re cute", []),
    ("mi gato se metió en la lavadora", []),
    ("¿viste qué tierno mi perrito?", []),
    ("le voy a tomar foto a mi gato", []),
    ("mi mamá me dejó tener mascota", []),
    ("ya casi es navidad", []),
    ("ya casi es mi cumpleaños", []),
    ("vamos a hacer fiesta de pijamada", []),
    ("la pijamada estuvo buenísima", []),
    ("comimos pizza en la fiesta", []),
    ("nos desvelamos viendo pelis", []),
    ("vimos stranger things toda la noche", []),
    ("¿ya viste la nueva temporada?", []),
    ("está buena la serie de netflix", []),
    ("estoy viendo un anime nuevo", []),
    ("mi favorito es demon slayer", []),
    ("terminé de leer un libro", []),
    ("leo mucho wattpad", []),
    ("¿tienes wattpad?", []),
    ("leo fanfics de bts", []),
    ("soy army", []),
    ("mi bias es jungkook", []),
    ("¿de qué fandom eres?", []),
    ("fuimos al bautizo de mi primo", []),
    ("se casó mi tía el sábado", []),
    ("mi abuelo cumplió años", []),
    ("mi hermana se va a graduar", []),
    ("tengo que estudiar para el examen", []),
    ("reprobé el bimestre", []),
    ("mis papás me van a matar", []),
    ("sáquenme de aquí", []),
    ("estoy harta de la tarea", []),
    ("no quiero ir a la escuela mañana", []),
    ("no me quiero levantar", []),
    ("tengo sueño", []),
    ("ya me voy a dormir", []),
    ("buenas noches", []),
    ("hasta mañana", []),
    ("no puedo dormir", []),
    ("ya son las 12", []),
    ("me dormí tardísimo", []),
    ("mi mamá me despertó temprano", []),
    ("hoy me levanté bien temprano", []),
    ("desayuné cereal", []),
    ("comí chilaquiles en el recreo", []),
    ("me muero de hambre", []),
    ("¿ya comiste?", []),
    ("voy a calentar sopa", []),
    ("me voy a bañar", []),
    ("salí de bañarme", []),
    ("tengo que hacer quehacer", []),
    ("mi mamá me puso a barrer", []),
    ("lavé los trastes", []),
    ("limpié mi cuarto", []),
    ("mi cuarto está hecho un desastre", []),
    ("ando escuchando música", []),
    ("spotify me está fallando", []),
    ("¿cuál es tu playlist favorita?", []),
    ("te paso mi playlist de tiktok", []),
    ("¿qué escuchas?", []),
    ("escucho de todo", []),
    ("me gusta el pop", []),
    ("me gusta la banda", []),
    ("escucho k-pop", []),
    ("soy fan de blackpink", []),
    ("amo a jimin", []),
    ("¿ya viste el nuevo mv?", []),
    ("está buena la canción", []),
    ("nos cancelaron el concierto", []),
    ("no me dejan ir al concierto", []),
    ("mi papá no me dejó ir", []),
    ("mi mamá me dio permiso", []),
    ("tengo permiso de llegar tarde", []),
    ("me dejan desvelar el viernes", []),
    ("mañana hay puente", []),
    ("no hay clases el lunes", []),
    ("me vacacioné una semana", []),
    ("me aburro en vacaciones", []),
    ("no tengo nada que hacer", []),
    ("vamos a salir al centro", []),
    ("vamos a la plaza", []),
    ("¿nos vemos en el mall?", []),
    ("quedamos en starbucks", []),
    ("compré un frappé", []),
    ("probé unos takis", []),
    ("se me antojaron unos tacos", []),
    ("vamos por unas tortas", []),
    ("pedí sushi", []),
    ("me encanta la pizza", []),
    ("me choca la verdura", []),
    ("no me gustan los ejotes", []),
    ("mi mamá cocina rico", []),
    ("odio los lunes", []),
    ("amo los viernes", []),
    ("ya casi es fin de semana", []),
    ("el tiempo pasa lento", []),
    ("el tiempo vuela", []),
    ("ya no sé qué hacer", []),
    ("me aburro en mi casa", []),
    ("está lloviendo feo", []),
    ("hace mucho calor", []),
    ("hace mucho frío", []),
    ("se fue la luz", []),
    ("regresó la luz", []),
    ("se me olvidó decirte", []),
    ("luego te cuento", []),
    ("te cuento al rato", []),
    ("luego hablamos", []),
    ("bye ya me voy", []),
    ("nos vemos mañana", []),
    ("cuidate", []),
    ("tqm amiga", []),
    ("tkm bestie", []),
    ("besitos", []),
    ("abrazos", []),
    ("xoxo", []),
    ("que duermas bien", []),
    ("que tengas buen día", []),
    ("que te vaya bien en tu examen", []),
    ("suerte con tu tarea", []),
    ("ánimo amiga", []),
    ("todo va a estar bien", []),
    ("cuenta conmigo", []),
    ("aquí estoy para ti", []),
    ("sabes que te quiero amiga", []),
    ("bestie forever", []),
]
